/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadegreeassignment;

import javax.swing.ImageIcon;
import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    ImageIcon imageMale = new ImageIcon("MaleUser.png");

    People SelectedAcc;

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();
        txtUsername.setBackground(new Color(0, 0, 0, 0));
        txtPassword.setBackground(new Color(0, 0, 0, 0));

        //changes the label to the icon
        this.setLocationRelativeTo(null);
        LblMaleUser.setText("");
        LblMaleUser.setIcon(imageMale);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();
        btnSignUp = new keeptoo.KButton();
        LblMaleUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("username");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsername.setCaretColor(new java.awt.Color(204, 0, 255));
        txtUsername.setName(""); // NOI18N
        txtUsername.setOpaque(false);
        kGradientPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 280, 40));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPassword.setCaretColor(new java.awt.Color(204, 0, 255));
        txtPassword.setName(""); // NOI18N
        txtPassword.setOpaque(false);
        kGradientPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 280, 40));

        btnLogin.setText("Login");
        btnLogin.setkBorderRadius(40);
        btnLogin.setkEndColor(new java.awt.Color(0, 204, 204));
        btnLogin.setkFillButton(false);
        btnLogin.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnLogin.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnLogin.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnLogin.setkStartColor(new java.awt.Color(255, 255, 255));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 150, 40));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("or");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        btnSignUp.setText("SignUp");
        btnSignUp.setkBorderRadius(40);
        btnSignUp.setkEndColor(new java.awt.Color(0, 204, 204));
        btnSignUp.setkFillButton(false);
        btnSignUp.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnSignUp.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnSignUp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnSignUp.setkPressedColor(new java.awt.Color(204, 102, 255));
        btnSignUp.setkStartColor(new java.awt.Color(255, 255, 255));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 150, 40));

        LblMaleUser.setText("jLabel4");
        kGradientPanel1.add(LblMaleUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 90, 80));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("password");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        // TODO add your handling code here:
        SignUp regist = new SignUp();
        regist.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        //Declares the strings so that repeated typing would not be needed
        String username = txtUsername.getText().trim();
        char[] password = txtPassword.getPassword();

        if (username.equals("staff") && (String.valueOf(password).equals("123"))) {
            txtUsername.setText(null);
            txtPassword.setText(null);
            Personnel_Home personnel_home = new Personnel_Home();
            personnel_home.setVisible(true);
            this.dispose();
            return;
        }

        if (username.isBlank() || txtPassword.getPassword().length == 0) {
            //Displays a popupbox
            JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {

            //Gets the list of Account text files to scan 
            //Gets the list of textfiles
            File Accountfolder = new File("./Accounts");
            File[] AccountList = Accountfolder.listFiles();

            for (int i = 0; AccountList.length > i; i++) {

                People AccountFiles = new People(AccountList[i].getName());

                if (username.equals(AccountFiles.GetUsername())) {
                    if (String.valueOf(txtPassword.getPassword()).equals(AccountFiles.GetPassword())) {

                        // changes the frame to the people home frame
                        People_Home people_home = new People_Home(AccountFiles);

                        people_home.setVisible(true);
                        this.dispose();
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "The credentials you have entered are incorrect. Please try again.", "Incorrect Credentials", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "I/O ERROR", "Failed to read the file", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblMaleUser;
    private keeptoo.KButton btnLogin;
    private keeptoo.KButton btnSignUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
