/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadegreeassignment;

import javax.swing.JOptionPane;
import java.io.File;
import java.time.format.DateTimeFormatter;
import static javadegreeassignment.CreateAppointment.stripExtension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.MutableComboBoxModel;

/**
 *
 * @author USER
 */
public class People_MakeAppointment extends javax.swing.JFrame {

    People AccData;
    String Username;
    String Status;
    Appointment ApptData;
    
    //Gets the list of Account text files to scan
    File Accountfolder = new File("./Accounts");
    File[] AccountList = Accountfolder.listFiles();

    //Gets the list of Appointment text files to scan
    File Appointmentfolder = new File("./Appointment");
    File[] AppointmentList = Appointmentfolder.listFiles();

    //Gets the list of Vaccine Text files to scan
    File Vaccinefolder = new File("./Vaccine");
    File[] VaccineList = Vaccinefolder.listFiles();

    //Gets the list of Center Text files to scan
    File Centerfolder = new File("./Center");
    File[] CenterList = Centerfolder.listFiles();

    static String[] stripExtension(String str) {
        // Handle null case specially.

        if (str == null) {
            return null;
        }

        // Get position of last '.'.
        int pos = str.lastIndexOf(".");
        
        String[] ToBeReturn = new String[2];
        ToBeReturn[0] = str.substring(0,pos);
        ToBeReturn[1] = str;
        
        // Otherwise return the string, up to the dot.
        return ToBeReturn;
    }
    
    /**
     * Creates new form People_MakeAppointment
     */
    
    
    
    public People_MakeAppointment(People Account) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.AccData=Account;
        //this.ApptData=Appt;
        
        
        this.Username=AccData.GetUsername();
        
        TxtAccName.setText(AccData.GetName());
        TxtIC.setText(AccData.GetIC());
        
        //Filling the combobox
        //Looping the creation of the array needed for the combo box model
        String[] CbModel = new String[VaccineList.length];
        String[] CbIndex = new String[VaccineList.length];
        for (int s = 0; s < VaccineList.length; s++) {
            
            CbModel[s] = stripExtension(VaccineList[s].getName())[0];
            CbIndex[s] = stripExtension(VaccineList[s].getName())[1];
        }

        MutableComboBoxModel model = new DefaultComboBoxModel(CbModel);

        CbBxVx.setModel(model);
        
        System.out.println(CbIndex[1]);
        System.out.println(CbIndex[2]);
        System.out.println(CbIndex[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        LblIC5 = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        CbBxVx = new javax.swing.JComboBox<>();
        BtnCrt = new keeptoo.KButton();
        TxtBx = new com.github.lgooddatepicker.components.DatePicker();
        TxtIC = new javax.swing.JTextField();
        LblPgeTtle5 = new javax.swing.JLabel();
        LblPgeTtle6 = new javax.swing.JLabel();
        LblIC2 = new javax.swing.JLabel();
        LblIC3 = new javax.swing.JLabel();
        CbBxTime = new javax.swing.JComboBox<>();
        BtnCncl = new keeptoo.KButton();
        LblIC4 = new javax.swing.JLabel();
        LblAccName = new javax.swing.JLabel();
        TxtSpecialRequest = new javax.swing.JTextField();
        TxtAccName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Make Appointment");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        LblIC5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LblIC5.setText("Vaccine");

        LblEmail.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LblEmail.setText("IC/Passport No");

        CbBxVx.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CbBxVx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stadium Bukit Jalil (Astrazaneca)", "WPCC  (Phizer)", "KL Convention Center(Moderna)" }));
        CbBxVx.setOpaque(false);

        BtnCrt.setText("Create");
        BtnCrt.setToolTipText("");
        BtnCrt.setkBackGroundColor(new java.awt.Color(30, 51, 102));
        BtnCrt.setkEndColor(new java.awt.Color(30, 51, 102));
        BtnCrt.setkHoverEndColor(new java.awt.Color(80, 51, 132));
        BtnCrt.setkHoverForeGround(new java.awt.Color(102, 255, 255));
        BtnCrt.setkHoverStartColor(new java.awt.Color(101, 83, 250));
        BtnCrt.setkStartColor(new java.awt.Color(81, 83, 250));
        BtnCrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCrtMouseClicked(evt);
            }
        });

        TxtIC.setEditable(false);
        TxtIC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtIC.setCaretColor(new java.awt.Color(204, 0, 255));
        TxtIC.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        TxtIC.setOpaque(false);

        LblPgeTtle5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblPgeTtle5.setForeground(new java.awt.Color(51, 51, 51));
        LblPgeTtle5.setText("Appointment Info");

        LblPgeTtle6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblPgeTtle6.setForeground(new java.awt.Color(51, 51, 51));
        LblPgeTtle6.setText("Account Info");

        LblIC2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LblIC2.setText("Date");

        LblIC3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LblIC3.setText("Time");

        CbBxTime.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CbBxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10.00 a.m", "2.00 p.m", "5.00 p.m" }));
        CbBxTime.setOpaque(false);

        BtnCncl.setText("Cancel");
        BtnCncl.setToolTipText("");
        BtnCncl.setkBackGroundColor(new java.awt.Color(30, 51, 102));
        BtnCncl.setkEndColor(new java.awt.Color(30, 51, 102));
        BtnCncl.setkHoverEndColor(new java.awt.Color(80, 51, 132));
        BtnCncl.setkHoverForeGround(new java.awt.Color(102, 255, 255));
        BtnCncl.setkHoverStartColor(new java.awt.Color(101, 83, 250));
        BtnCncl.setkStartColor(new java.awt.Color(81, 83, 250));
        BtnCncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCnclActionPerformed(evt);
            }
        });

        LblIC4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LblIC4.setText("Special Request");

        LblAccName.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LblAccName.setText("Account Name");

        TxtSpecialRequest.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        TxtSpecialRequest.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtSpecialRequest.setCaretColor(new java.awt.Color(204, 0, 255));
        TxtSpecialRequest.setOpaque(false);

        TxtAccName.setEditable(false);
        TxtAccName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtAccName.setCaretColor(new java.awt.Color(204, 0, 255));
        TxtAccName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        TxtAccName.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPgeTtle5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblIC2)
                        .addGap(419, 419, 419)
                        .addComponent(LblIC3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(CbBxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblIC4)
                        .addGap(367, 367, 367)
                        .addComponent(LblIC5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtSpecialRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(CbBxVx, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblPgeTtle6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblAccName)
                        .addGap(371, 371, 371)
                        .addComponent(LblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtAccName, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(TxtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCncl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(BtnCrt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblPgeTtle6)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblAccName)
                    .addComponent(LblEmail))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAccName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(LblPgeTtle5)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblIC2)
                    .addComponent(LblIC3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbBxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblIC4)
                    .addComponent(LblIC5))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtSpecialRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbBxVx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCncl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCnclActionPerformed
        // Changes the frame back to the Personnel Home page:
        People_Home people_home = new People_Home(this.AccData);
        people_home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCnclActionPerformed

    private void BtnCrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCrtMouseClicked

        String AccountName = TxtAccName.getText().trim();
        String IC = TxtIC.getText().trim();
        String Request = TxtSpecialRequest.getText().trim();
        String time = String.valueOf(CbBxTime.getSelectedItem());

        String location = String.valueOf(CbBxVx.getSelectedItem()) + ".txt";

        //Ensures that there are no empty data fields
        if (AccountName.isBlank() || IC.isBlank() || TxtBx.getDate() == null
            || time.isBlank() || location.isBlank()) {

            JOptionPane.showMessageDialog(this, "Please ensure that all the data fields are filled in.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String date = TxtBx.getDate().format(DateTimeFormatter.ISO_DATE);
        try {
            try {

                //https://stackoverflow.com/questions/5694385/getting-the-filenames-of-all-files-in-a-folder
                //loops the scanning to see if there are duplicates
                for (int i = 0; i < AppointmentList.length; i++) {

                    Appointment AppointmentFiles = new Appointment(AppointmentList[i].getName());

                    //Checks if there is already a record of the account
                    if ((AppointmentFiles.GetTempName().equals(AccountName))) {
                        if (AppointmentFiles.GetTempIC().equals(IC)) {

                            JOptionPane.showMessageDialog(this, "This account already has an appointment", "ERROR", JOptionPane.ERROR_MESSAGE);
                            return;

                        }
                    }
                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, "Failed to check for duplicate data.", "Error: Failed to Save", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
            try {

                //https://stackoverflow.com/questions/5694385/getting-the-filenames-of-all-files-in-a-folder
                //loops the scanning to get the Name and IC of the textfile
                for (int i = 0; i < AccountList.length; i++) {

                    People AccountFiles = new People(AccountList[i].getName());

                    //Checks if the account exists

                     if ((AccountFiles.GetName().equals(AccountName))) {
                        if (AccountFiles.GetIC().equals(IC)) {
                            //loops the scanning of the vaccine text files to find a match
                            for (int n = 0; n < VaccineList.length; n++) {

                                Vaccines VaxFiles = new Vaccines(VaccineList[i].getName());

                                //Creates People Object that is to be saved in a text file
                                Appointment newAppt = new Appointment(date, Request, time, VaxFiles, AccountFiles);

                                //Invokes the CreateAccount function which save the data into a text file
                                newAppt.CreateReport();
                            }
                            }
                            else if ((!AccountFiles.GetName().equals(AccountName)) || (!AccountFiles.GetIC().equals(IC))) {

                            JOptionPane.showMessageDialog(this, "This account does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
                            return;
                    } 
                     }   
                }
                } catch (Exception e) {

                JOptionPane.showMessageDialog(this, "Failed to write data in textfile.", "Error: Failed to Save", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            
                }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Failed to create the appointment.", "Error: Failed to Save", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        new People_Home(this.AccData).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCrtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(People_MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(People_MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(People_MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(People_MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new People_MakeAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton BtnCncl;
    private keeptoo.KButton BtnCrt;
    private javax.swing.JComboBox<String> CbBxTime;
    private javax.swing.JComboBox<String> CbBxVx;
    private javax.swing.JLabel LblAccName;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblIC2;
    private javax.swing.JLabel LblIC3;
    private javax.swing.JLabel LblIC4;
    private javax.swing.JLabel LblIC5;
    private javax.swing.JLabel LblPgeTtle5;
    private javax.swing.JLabel LblPgeTtle6;
    private javax.swing.JTextField TxtAccName;
    private com.github.lgooddatepicker.components.DatePicker TxtBx;
    private javax.swing.JTextField TxtIC;
    private javax.swing.JTextField TxtSpecialRequest;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
